[core]
POSTGRES_URI = "postgresql://diroot:BqxYUgqDKDTAQZXa1NMT@localhost:23503/postgres"

[admin]
user = "db_admin"
password = "ChangeMeAdmin123"

[[databases]]
db_name = "outhouse"

[[databases.users]]
user = "ohowner"
password = "ChangeMeOwner123"
role = "owner"

[[databases.users]]
user = "ohapp"
password = "ChangeMeOwner123"
role = "read_write_create"

[[databases.users]]
user = "ohreader"
password = "ChangeMeRead123"
role = "read_write"
